waypoints=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
num_waypoints=0

while 1:

if new_waypts_flag==1:
 waypoints=new_waypts
 num_waypoints=waypoints[0]
 new_waypts_flag=0
end

i=1
while i<= num_waypoints:
  joints = [waypoints[i], waypoints[i+1], waypoints[i+2], waypoints[i+3], waypoints[i+4], waypoints[i+5]]
  movep(joints, v=0.05, r=0.1)
  i=i+6
end

if num_waypoints==0:
 sleep(0.01)
end

end